import fs from 'fs';
import path from 'path';
import { createHash } from 'crypto';
import { KTX_VERSION } from './ktxTool';
import { AEK_ASSETS_DIR, getOutputFile } from './outputs';
import { ROOT } from './sources';
import type { BuiltLodChain } from './lodChains';
import type { EncodedTexture } from './textures';

/**
 * The content-hash cache (p300 §7). An encode is keyed by everything that decides its bytes:
 * the source bytes (every file a pack reads, a .gltf's external files), the settings that apply
 * (sorted keys), the asset's own inputs (sRGB, `importTextures`, a GLB's resolved `lodChain` with
 * the simplifier and LOD format versions, the output's logical path), {@link PIPELINE_VERSION} and
 * the pinned tool versions. Two tiers:
 * - `assets.lock.json` (committed, like the outputs it points to, DD3): key → output URL and the
 *   result's metadata. A hit needs the entry and its file in `aek-assets/`, nothing else: a clone
 *   without `.cache/` or `ktx` uses the committed outputs as they are.
 * - `.cache/asset-pipeline/store/<key>/` (gitignored): the output and its entry, so an output that
 *   the stale cleanup removed (eg. a profile switched back and forth) is copied back, not encoded.
 */

/**
 * Bump when a change to the pipeline's code changes what it writes for the same inputs (eg. the
 * resize filter, the `ktx create` options, a glTF transform). Every asset then encodes once more.
 */
export const PIPELINE_VERSION = 1;

export const ASSETS_LOCK_FILE = path.join(ROOT, 'assets.lock.json');
export const CACHE_STORE_DIR = path.join(ROOT, '.cache', 'asset-pipeline', 'store');

const LOCK_NOTE =
  'Generated by the asset pipeline (p300 §7): cache key → output in src/public/aek-assets/. Commit it with the outputs; never edit it by hand.';

/** What a hit restores: a result's output and metadata (the settings are resolved again). */
export type CacheEntry = {
  /** The source file, or a pack's JSON, '/'-separated from the repo root (for reading diffs) */
  source: string;
  /** The output's root-absolute URL */
  url: string;
  bytes: number;
  textures?: EncodedTexture[];
  droppedTextures?: number;
  geometryBytes?: { in: number; out: number };
  /** A GLB's LOD chains (p347 Phase 3), for the generated data's `__lodChain` */
  lodChains?: BuiltLodChain[];
  warnings?: string[];
  /** The `ktx` that encoded it, when one did (the key has the pinned version) */
  ktxVersion?: string;
};

type LockFile = { '//': string; entries: Record<string, CacheEntry> };

/** JSON with sorted object keys and without undefined values: equal values, equal strings */
export const stableStringify = (value: unknown): string =>
  JSON.stringify(value, (_key, v: unknown) =>
    v && typeof v === 'object' && !Array.isArray(v)
      ? Object.fromEntries(
          Object.entries(v as Record<string, unknown>).sort(([a], [b]) => (a < b ? -1 : 1))
        )
      : v
  );

const readPackageVersion = (name: string) =>
  (
    JSON.parse(fs.readFileSync(path.join(ROOT, 'node_modules', name, 'package.json'), 'utf-8')) as {
      version: string;
    }
  ).version;

let toolVersions: Record<'texture' | 'importedAsset', Record<string, string | number>> | null =
  null;

/**
 * The versions an asset type's output depends on. sharp decodes every source image, `ktx` encodes
 * KTX2; a GLB also goes through gltf-transform and its codecs. A gltf-transform update therefore
 * doesn't re-encode the standalone textures.
 */
const getToolVersions = (type: 'texture' | 'importedAsset') => {
  if (!toolVersions) {
    const texture = {
      pipeline: PIPELINE_VERSION,
      ktx: KTX_VERSION,
      sharp: readPackageVersion('sharp'),
    };
    toolVersions = {
      texture,
      importedAsset: {
        ...texture,
        gltfTransform: readPackageVersion('@gltf-transform/core'),
        meshoptimizer: readPackageVersion('meshoptimizer'),
        draco3dgltf: readPackageVersion('draco3dgltf'),
      },
    };
  }
  return toolVersions[type];
};

/**
 * Keys computed in this process, by their inputs and their files' size and mtime: the dev server
 * looks every asset up again on each asset change (Phase 3), and a key reads all its source bytes.
 */
const keyMemo = new Map<string, string>();
const KEY_MEMO_LIMIT = 1000;

/**
 * An encode's cache key (SHA-256, hex).
 * @param input.files Every source file the encode reads, in a fixed order
 * @param input.params Every other input: the settings that apply, the asset's own inputs and the
 * output's logical path (so the key decides the output's name too)
 */
export const getCacheKey = (input: {
  type: 'texture' | 'importedAsset';
  files: string[];
  params: unknown;
}) => {
  const inputs = stableStringify({ tools: getToolVersions(input.type), params: input.params });
  const fileStats = input.files.map((file) => {
    const stat = fs.statSync(file);
    return `${file}\0${stat.size}\0${stat.mtimeMs}`;
  });
  const memoKey = `${inputs}\0${fileStats.join('\0')}`;
  const memoized = keyMemo.get(memoKey);
  if (memoized) return memoized;

  const hash = createHash('sha256');
  hash.update(inputs);
  for (const file of input.files) {
    const bytes = fs.readFileSync(file);
    hash.update(`\0${bytes.byteLength}\0`).update(bytes);
  }
  const key = hash.digest('hex');
  if (keyMemo.size >= KEY_MEMO_LIMIT) keyMemo.clear();
  keyMemo.set(memoKey, key);
  return key;
};

const writeFileAtomic = (file: string, bytes: Uint8Array | string) => {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const tempFile = `${file}.${process.pid}.tmp`;
  fs.writeFileSync(tempFile, bytes);
  fs.renameSync(tempFile, file);
};

const readLockEntries = (lockFile: string): Record<string, CacheEntry> => {
  if (!fs.existsSync(lockFile)) return {};
  try {
    return (JSON.parse(fs.readFileSync(lockFile, 'utf-8')) as LockFile).entries ?? {};
  } catch (error) {
    throw new Error(
      `${path.relative(ROOT, lockFile)}: invalid JSON (${(error as Error).message}). Resolve its merge conflict by taking either side, or delete it: the next run re-encodes what it's missing.`
    );
  }
};

const isOutputPresent = (entry: CacheEntry) => {
  const file = getOutputFile(entry.url);
  return fs.existsSync(file) && fs.statSync(file).size === entry.bytes;
};

/** Only outputs in aek-assets/ are stored: a public source used as it is isn't an output. */
const isAekAsset = (file: string) => file.startsWith(AEK_ASSETS_DIR + path.sep);

export type CacheHit = { entry: CacheEntry; from: 'output' | 'store' };

export type PipelineCache = ReturnType<typeof createPipelineCache>;

/**
 * One run's cache: the lock is read once and written by {@link PipelineCache.save}, merged over
 * the file as it is then, so two runs at once (eg. `yarn assets` while the dev server re-encodes
 * a changed source) keep each other's entries.
 * @param opts.lockFile / opts.storeDir Other locations (tests)
 */
export const createPipelineCache = (opts: { lockFile?: string; storeDir?: string } = {}) => {
  const lockFile = opts.lockFile ?? ASSETS_LOCK_FILE;
  const storeDir = opts.storeDir ?? CACHE_STORE_DIR;
  const entries = readLockEntries(lockFile);
  /** Entries this run added or restored from the store, written by `save` */
  const changed = new Map<string, CacheEntry>();
  /** Entries `prune` dropped */
  const removed = new Set<string>();
  /** Keys this run looked up */
  const used = new Set<string>();

  const getStoreEntryDir = (key: string) => path.join(storeDir, key);

  /** Copies a stored output back to its place, or returns false when it isn't stored. */
  const restoreFromStore = (key: string, entry: CacheEntry) => {
    const stored = path.join(getStoreEntryDir(key), path.basename(entry.url));
    if (!fs.existsSync(stored) || fs.statSync(stored).size !== entry.bytes) return false;
    writeFileAtomic(getOutputFile(entry.url), fs.readFileSync(stored));
    return true;
  };

  const readStoreEntry = (key: string): CacheEntry | null => {
    const file = path.join(getStoreEntryDir(key), 'entry.json');
    if (!fs.existsSync(file)) return null;
    try {
      return JSON.parse(fs.readFileSync(file, 'utf-8')) as CacheEntry;
    } catch {
      return null;
    }
  };

  return {
    /**
     * The output for a key, or null (a miss). A lock entry whose output is missing is restored
     * from the store; a key the lock lacks (eg. encoded on another branch) is taken from the store.
     */
    get(key: string): CacheHit | null {
      used.add(key);
      const locked = removed.has(key) ? undefined : changed.get(key) ?? entries[key];
      if (locked && isOutputPresent(locked)) return { entry: locked, from: 'output' };
      const entry = locked ?? readStoreEntry(key);
      if (!entry) return null;
      if (!isOutputPresent(entry)) {
        if (!isAekAsset(getOutputFile(entry.url)) || !restoreFromStore(key, entry)) return null;
      }
      if (!locked) changed.set(key, entry);
      return { entry, from: 'store' };
    },

    /** Records an encode's output: in the lock (on `save`) and in the store. */
    set(key: string, entry: CacheEntry) {
      used.add(key);
      removed.delete(key);
      changed.set(key, entry);
      const file = getOutputFile(entry.url);
      const dir = getStoreEntryDir(key);
      if (!isAekAsset(file) || fs.existsSync(path.join(dir, 'entry.json'))) return;
      // Written into a temp folder and renamed, so a stored entry is never half there
      const tempDir = `${dir}.${process.pid}.tmp`;
      fs.rmSync(tempDir, { recursive: true, force: true });
      fs.mkdirSync(tempDir, { recursive: true });
      fs.copyFileSync(file, path.join(tempDir, path.basename(entry.url)));
      fs.writeFileSync(path.join(tempDir, 'entry.json'), JSON.stringify(entry, null, 2));
      try {
        fs.renameSync(tempDir, dir);
      } catch {
        // Another run stored the same key first: same inputs, same content
        fs.rmSync(tempDir, { recursive: true, force: true });
      }
    },

    /**
     * Drops the lock entries this run didn't look up. Only for the end of a full, successful run
     * (with `removeStaleOutputs`); never for a single asset. The store keeps them.
     */
    prune() {
      for (const key of Object.keys(entries)) if (!used.has(key)) removed.add(key);
      for (const key of changed.keys()) if (!used.has(key)) changed.delete(key);
    },

    /** Writes the lock when this run changed it: the file as it is now, plus this run's changes. */
    save() {
      if (!changed.size && !removed.size) return;
      const merged = { ...readLockEntries(lockFile), ...Object.fromEntries(changed) };
      for (const key of removed) delete merged[key];
      const sorted = Object.fromEntries(
        Object.entries(merged).sort(([a], [b]) => (a < b ? -1 : 1))
      );
      const lock: LockFile = { '//': LOCK_NOTE, entries: sorted };
      writeFileAtomic(lockFile, `${JSON.stringify(lock, null, 2)}\n`);
      for (const [key, entry] of changed) entries[key] = entry;
      for (const key of removed) delete entries[key];
      changed.clear();
      removed.clear();
    },
  };
};
